# Generated by Django 3.2.9 on 2022-04-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211203_1240'),
        ('blog', '0002_blogpost_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Blog',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='blogpost',
            new_name='blog',
        ),
    ]
